// Hello-world stand-in for the real DAG execution engine.
//
// This placeholder exists so the full hpcctl lifecycle (boot -> deploy -> submit ->
// status -> destroy) can be exercised end to end before the real engine is written.
// It honours the real engine's command-line contract -- `engine --dag <path>` is
// exactly what the sbatch script generated by `hpcctl submit` invokes -- and it
// proves the runtime physics the real engine will depend on: every rank comes up
// under `srun --mpi=pmix`, the DAG file staged on the shared filesystem is readable
// from the node the scheduler rank landed on, and ranks span multiple hosts.
//
// By engine convention the scheduler is the HIGHEST rank (size - 1); cyclic placement
// puts it on the first instance beside worker rank 0. A run is healthy when every rank
// prints its hello line across more than one hostname and the scheduler rank ends with
// `ENGINE_OK ranks=<N> ...`. A rank-0-only run is the signature of an MPI stack
// mismatch between compile time and launch time.

#include <mpi.h>

#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>

namespace {

// Returns the --dag argument, or an empty string when it is absent.
std::string dag_path_from_args(int argc, char **argv) {
    for (int i = 1; i + 1 < argc; ++i) {
        if (std::strcmp(argv[i], "--dag") == 0) {
            return argv[i + 1];
        }
    }
    return "";
}

}  // namespace

int main(int argc, char **argv) {
    MPI_Init(&argc, &argv);

    int rank = 0;
    int size = 0;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    char host[MPI_MAX_PROCESSOR_NAME];
    int host_len = 0;
    MPI_Get_processor_name(host, &host_len);

    const std::string dag_path = dag_path_from_args(argc, argv);

    // The scheduler rank validates the input contract before anyone does work, mirroring
    // how the real engine will deserialise at the scheduler and broadcast. Schema *parsing*
    // failures are the engine's job; schema *logic* failures were Python's and never get here.
    const int scheduler = size - 1;
    long long dag_bytes = -1;
    if (rank == scheduler) {
        if (dag_path.empty()) {
            std::fprintf(stderr, "engine: missing required argument: --dag <path>\n");
            MPI_Abort(MPI_COMM_WORLD, 2);
        }
        std::ifstream dag(dag_path, std::ios::binary | std::ios::ate);
        if (!dag) {
            std::fprintf(stderr, "engine: cannot read DAG file: %s\n", dag_path.c_str());
            MPI_Abort(MPI_COMM_WORLD, 3);
        }
        dag_bytes = static_cast<long long>(dag.tellg());
    }

    std::printf("hello from rank %d of %d on %s\n", rank, size, host);

    MPI_Barrier(MPI_COMM_WORLD);
    if (rank == scheduler) {
        // The batch script runs the job with cwd set to a per-job result directory on the
        // shared filesystem; files written to cwd are downloaded by `hpcctl result <job id>`.
        // The real engine will emit its timings and scheduling telemetry the same way.
        std::ofstream result_file("engine_result.txt");
        if (result_file) {
            result_file << "ranks=" << size << "\ndag=" << dag_path << "\nbytes=" << dag_bytes
                        << "\n";
        } else {
            std::fprintf(stderr, "engine: warning: could not write engine_result.txt\n");
        }
        std::printf("ENGINE_OK ranks=%d dag=%s bytes=%lld\n", size, dag_path.c_str(), dag_bytes);
    }

    MPI_Finalize();
    return 0;
}
